version: '3'
volumes:
  db-data:
services:
  web:
    image: nginx
    container_name: nginx
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - ${PORT_NGINX}:80
    depends_on:
      - php
      - db
  php:
    image: yiisoftware/yii2-php:7.2-fpm
    container_name: php
    volumes:
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/base.ini
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/app
  db:
    image: mysql:5.7
    container_name: ${DB_HOST}
    command: --max_allowed_packet=32505856
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - ${PORT_PHPMYADMIN}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
    depends_on:
      - db
